export { default as Login } from "./Auth/Login";
export { default as Register } from "./Auth/Register";
export { default as Modal } from "./Modals/Modal";
export { default as AddLocationForm } from "./DashboardForms/AddLocationForm";
export { default as Locations } from "./LocationActivity/Locations";
export { default as AddCarosuselImageForm } from "./DashboardForms/AddCarosuselImageForm";
export { default as CarouselActivities } from "./CarouselActivities/CarouselActivities";
export { default as CarouselStaff } from "./CarouselStaff/CarouselStaff";
export { default as AddStaffCarouselForm } from "./DashboardForms/AddStaffCarouselForm";
export { default as AddCarouselFlyerForm } from "./DashboardForms/AddCarouselFlyerForm";
export { default as CarouselFlyer } from "./CarouselFlyer/CarouselFlyer";
export { default as RestaurantsBars } from "./Restaurantsbars/RestaurantsBars";
export { default as AddRestaurantImageForm } from "./DashboardForms/AddRestaurantImageForm";
export { default as RestaurantsSpecsServiceForm } from "./DashboardForms/RestaurantsSpecsServiceForm";
export { default as RestaurantsSpecsMembersForm } from "./DashboardForms/RestaurantsSpecsMembersForm";
export { default as RestaurantsSpecsTypeForm } from "./DashboardForms/RestaurantsSpecsTypeForm";
export { default as RestaurantsSpecsMembers } from "./Restaurantsbars/RestaurantsSpecsMembers";
export { default as RestaurantsSpecsService } from "./Restaurantsbars/RestaurantsSpecsService";
export { default as RestaurantsSpecsType } from "./Restaurantsbars/RestaurantsSpecsType"
export {default as RestaurantsSpecsRender} from "./DashboardForms/RestaurantsSpecsRender"